# Data Cleaning and Transformation with Python

## Objetivo

Este proyecto presenta un proceso de limpieza y transformación de datos utilizando Python y Pandas.

Se trabajó sobre un dataset en formato CSV aplicando técnicas de preprocesamiento para:

- explorar la estructura del conjunto de datos
- identificar valores faltantes
- reemplazar datos nulos
- eliminar columnas no relevantes
- validar la consistencia final del dataset

## Herramientas utilizadas

- Python
- Pandas
- Jupyter Notebook

## 1. Carga del dataset

En esta etapa se importa la librería Pandas y se carga el archivo CSV en un DataFrame para su análisis.

In [1]:
import pandas as pd
df = pd.read_csv('multilingual_mobile_app_reviews_2025.csv')
df.head()

,review_id,user_id,app_name,app_category,review_text,review_language,rating,review_date,verified_purchase,device_type,num_helpful_votes,user_age,user_country,user_gender,app_version
0,1,1967825,MX Player,Travel & Local,Qui doloribus consequuntur. Perspiciatis tempo...,no,1.3,2024-10-09 19:26:40,True,Android Tablet,65,14.0,China,Female,1.4
1,2,9242600,Tinder,Navigation,"Great app but too many ads, consider premium v...",ru,1.6,2024-06-21 17:29:40,True,iPad,209,18.0,Germany,Male,8.9
2,3,7636477,Netflix,Dating,The interface could be better but overall good...,es,3.6,2024-10-31 13:47:12,True,iPad,163,67.0,Nigeria,Male,2.8.37.5926
3,4,209031,Venmo,Productivity,"Latest update broke some features, please fix ...",vi,3.8,2025-03-12 06:16:22,True,iOS,664,66.0,India,Female,10.2
4,5,7190293,Google Drive,Education,"Perfect for daily use, highly recommend to eve...",tl,3.2,2024-04-21 03:48:27,True,iPad,1197,40.0,South Korea,Prefer not to say,4.7

## 2. Exploración inicial

Se inspecciona la estructura del dataset para conocer sus dimensiones y contenido.

In [4]:
import pandas as pd
df = pd.read_csv('multilingual_mobile_app_reviews_2025.csv')
df.head()

,review_id,user_id,app_name,app_category,review_text,review_language,rating,review_date,verified_purchase,device_type,num_helpful_votes,user_age,user_country,user_gender,app_version
0,1,1967825,MX Player,Travel & Local,Qui doloribus consequuntur. Perspiciatis tempo...,no,1.3,2024-10-09 19:26:40,True,Android Tablet,65,14.0,China,Female,1.4
1,2,9242600,Tinder,Navigation,"Great app but too many ads, consider premium v...",ru,1.6,2024-06-21 17:29:40,True,iPad,209,18.0,Germany,Male,8.9
2,3,7636477,Netflix,Dating,The interface could be better but overall good...,es,3.6,2024-10-31 13:47:12,True,iPad,163,67.0,Nigeria,Male,2.8.37.5926
3,4,209031,Venmo,Productivity,"Latest update broke some features, please fix ...",vi,3.8,2025-03-12 06:16:22,True,iOS,664,66.0,India,Female,10.2
4,5,7190293,Google Drive,Education,"Perfect for daily use, highly recommend to eve...",tl,3.2,2024-04-21 03:48:27,True,iPad,1197,40.0,South Korea,Prefer not to say,4.7

In [2]:
df.tail()

,review_id,user_id,app_name,app_category,review_text,review_language,rating,review_date,verified_purchase,device_type,num_helpful_votes,user_age,user_country,user_gender,app_version
2509,2510,2322118,OneDrive,Business,Счастье низкий пастух. Нож неожиданно поезд тр...,nl,3.0,2023-11-23 01:07:30,False,iOS,635,21.0,Malaysia,Non-binary,1.1.2-beta
2510,2511,2167693,Signal,Finance,This app is amazing! Really love the new featu...,ms,1.9,2025-06-05 16:42:20,True,Windows Phone,1127,38.0,Bangladesh,NaN,v12.0.80
2511,2512,5554467,OneDrive,Social Networking,This app is amazing! Really love the new featu...,zh,3.4,2024-06-15 05:02:18,True,Android Tablet,677,27.0,Pakistan,NaN,9.1.32.4821
2512,2513,8805125,Coursera,Social Networking,Invitare convincere pericoloso corsa fortuna. ...,da,2.7,2023-12-02 01:41:31,True,Android,155,35.0,India,NaN,v8.9.13
2513,2514,1099793,Venmo,Education,"Latest update broke some features, please fix ...",it,2.1,2025-03-04 02:51:17,True,Android,1040,26.0,Bangladesh,Prefer not to say,2.2

In [3]:
print(df.shape)

(2514, 15)

## 3. Detección de valores faltantes

Se identifican datos nulos o incompletos presentes en el conjunto de datos.

In [6]:
df.count() #revisa cuantos valores nulos hay en cada columna.

review_id            2514
user_id              2514
app_name             2514
app_category         2514
review_text          2455
review_language      2514
rating               2477
review_date          2514
verified_purchase    2514
device_type          2514
num_helpful_votes    2514
user_age             2514
user_country         2473
user_gender          1927
app_version          2484
dtype: int64

## 4. Tratamiento de valores nulos

Los valores faltantes son reemplazados para garantizar consistencia en el análisis.

In [7]:
df = df.fillna(0) #reemplaza todos los valores vacios (nulos o NAN) en la tabla df por ceros

In [8]:
df.count() #valores missing ya completados

review_id            2514
user_id              2514
app_name             2514
app_category         2514
review_text          2514
review_language      2514
rating               2514
review_date          2514
verified_purchase    2514
device_type          2514
num_helpful_votes    2514
user_age             2514
user_country         2514
user_gender          2514
app_version          2514
dtype: int64

In [9]:
print(df.columns) #muestra todas las columnas

Index(['review_id', 'user_id', 'app_name', 'app_category', 'review_text',
       'review_language', 'rating', 'review_date', 'verified_purchase',
       'device_type', 'num_helpful_votes', 'user_age', 'user_country',
       'user_gender', 'app_version'],
      dtype='object')

## 5. Eliminación de columnas irrelevantes

Se eliminan variables no necesarias para optimizar el procesamiento del dataset.

In [10]:
columns_to_drop = ['review_language','user_age','user_country']# borra tres columnas de la tabla df
df.drop(columns_to_drop, axis="columns", inplace=True) #inplace=True: hace el cambio directamente en df, sin crear una copia

In [12]:
print(df.isna().sum()) #te muestra cuantos valores faltan (vacios o NAN) hay en cada columna de la tabla df.

review_id            0
user_id              0
app_name             0
app_category         0
review_text          0
rating               0
review_date          0
verified_purchase    0
device_type          0
num_helpful_votes    0
user_gender          0
app_version          0
dtype: int64

## 6. Conclusión

El dataset fue limpiado y transformado correctamente, quedando preparado para análisis posteriores.

## Visualización extendida (opcional)

In [5]:
pd.set_option('display.max_rows', None) #muestra todas las filas
pd.set_option('display.max_columns', None) #muestra todas las columnas, aunque haya muchas

df

      review_id  user_id          app_name             app_category  \
0             1  1967825         MX Player           Travel & Local
1             2  9242600            Tinder               Navigation
2             3  7636477           Netflix                   Dating
3             4   209031             Venmo             Productivity
4             5  7190293      Google Drive                Education
5             6  2708513           Netflix            Music & Audio
6             7  5747119            Signal           Travel & Local
7             8  9361704             Canva        Social Networking
8             9  1794522  Microsoft Office  Video Players & Editors
9            10   638552           Dropbox         News & Magazines
10           11  7798256          Coursera               Navigation
11           12  2442608   Adobe Photoshop                Utilities
12           13  9518194             Udemy         Health & Fitness
13           14  9907725   Adobe Photoshop            Entertainment
14           15  6800828              eBay            Entertainment
15           16  2420821      Khan Academy           Travel & Local
16           17  1625206  Microsoft Office            Communication
17           18  5807197          Snapchat             Productivity
18           19  7394150          Facebook              Photography
19           20   154447              eBay  Video Players & Editors
20           21   426765          LinkedIn            Communication
21           22  5259230            PayPal  Video Players & Editors
22           23  4141154       Google Maps              Photography
23           24  1421324       Booking.com            Communication
24           25  8253566              Zoom                    Games
25           26  9037326            Reddit         Health & Fitness
26           27  7199076          Duolingo                    Games
27           28  3474754           YouTube            Music & Audio
28           29  6793979            Reddit         Health & Fitness
29           30  6364956      Khan Academy            Music & Audio
30           31  7674680            Tinder                  Finance
31           32  3869795              Waze                Utilities
32           33   452896         MX Player               Navigation
33           34  4772073      Khan Academy            Music & Audio
34           35  3694297            Signal        Social Networking
35           36  9680513          Coursera         Health & Fitness
36           37  4176817            PayPal               Navigation
37           38  1751177           Discord        Social Networking
38           39  9332926          Coursera           Travel & Local
39           40  9169560            Reddit                Utilities
40           41  1664689          Duolingo         Health & Fitness
41           42  6650190          Snapchat  Video Players & Editors
42           43  4885687         Instagram             Productivity
43           44  9424245           Spotify  Video Players & Editors
44           45  8264991   Adobe Photoshop                Utilities
45           46  5077931          OneDrive               Navigation
46           47  9817032          Coursera               Navigation
47           48  3526900             Udemy            Music & Audio
48           49  5371130            Reddit                   Dating
49           50  6740184            PayPal                Education
50           51  5175395           Spotify           Travel & Local
51           52  8974152               VLC               Navigation
52           53  9404682            PayPal                Utilities
53           54  1837893          OneDrive         Health & Fitness
54           55  4494880              Zoom                Education
55           56  6103042            Amazon                   Dating
56           57  4286414               VLC               Navigation
57           58  6033742   Adobe Photoshop                 Business
58           59  6917881         Pinterest                  Finance
59           60  2692974            Signal            Music & Audio
60           61  6517985           Netflix             Productivity
61           62  7996868            Bumble           Travel & Local
62           63  7822606           Netflix         News & Magazines
63           64  3918418           YouTube                 Business
64           65  3340180      Google Drive                    Games
65           66   128374             Venmo        Social Networking
66           67  3405700           Discord                Education
67           68  1273965           Netflix            Communication
68           69  5366630              Uber                   Dating
69           70  5138571            Airbnb                Utilities
70           71  6951696          LinkedIn              Photography
71           72  5060271         MX Player                Education
72           73  3318542           YouTube                    Games
73           74  6461002       Booking.com            Entertainment
74           75  3019694            Reddit            Communication
75           76  5149101             Canva             Productivity
76           77   106810             Canva            Entertainment
77           78  3626280          Duolingo               Navigation
78           79  5506444          Coursera              Photography
79           80  7518210          Snapchat                   Dating
80           81  8676076               VLC        Social Networking
81           82  9758155             Udemy         News & Magazines
82           83  6542089         Grammarly         News & Magazines
83           84  7525149       Booking.com                Utilities
84           85  8568772       Google Maps            Communication
85           86  7581188            Bumble             Productivity
86           87  8063715               VLC                 Business
87           88  4247994              Lyft                Utilities
88           89  4752512            PayPal                Utilities
89           90  8845959            Airbnb  Video Players & Editors
90           91  3979923         Pinterest         Health & Fitness
91           92  2663646          Snapchat           Travel & Local
92           93  1177581           YouTube                    Games
93           94  5651268            Tinder        Social Networking
94           95  7075534          LinkedIn                   Dating
95           96  7148838          Telegram                Education
96           97  9899226          Coursera            Communication
97           98  9129842               VLC           Travel & Local
98           99  9262579         Grammarly            Music & Audio
99          100  7846014           Dropbox            Communication
100         101   775419          Facebook           Travel & Local
101         102  4248725            Reddit                Education
102         103  2656551             Udemy                Education
103         104  8045036          Coursera                 Shopping
104         105  9561839              Uber        Social Networking
105         106  4399055       Booking.com            Entertainment
106         107  3427421           Netflix                Education
107         108  4174336              Uber         Health & Fitness
108         109  5159717         Grammarly            Communication
109         110  2130966          OneDrive             Productivity
110         111  1870648           YouTube                    Games
111         112  7813146          Snapchat             Productivity
112         113  7406261   Adobe Photoshop            Music & Audio
113         114  8853457          LinkedIn            Music & Audio
114         115  4735017            Amazon         News & Magazines
115         116  8767566       Booking.com                 Business
116         117  3331028          Snapchat         News & Magazines
117         118  9090305          Facebook             Productivity
118         119  3206298         Pinterest               Navigation
119         120  8223504            Amazon            Music & Audio
120         121  3916534             Udemy                Utilities
121         122  5171208          WhatsApp                 Shopping
122         123  9061299            Bumble  Video Players & Editors
123         124   863626           YouTube            Entertainment
124         125  5001239      Google Drive         Health & Fitness
125         126  8335577      Google Drive               Navigation
126         127  9731199          Telegram        Social Networking
127         128  8131491         MX Player            Music & Audio
128         129  3193109  Microsoft Office             Productivity
129         130  8114965            Airbnb                 Business
130         131  6822755            Signal                Utilities
131         132  9780808            Reddit                  Finance
132         133   999411            Tinder         Health & Fitness
133         134  6481684           Twitter         News & Magazines
134         135  5088757      Google Drive               Navigation
135         136  7294570              Waze                    Games
136         137  3983526            Airbnb                Education
137         138  4843227            TikTok           Travel & Local
138         139  1294198               VLC  Video Players & Editors
139         140  4538490         MX Player         News & Magazines
140         141  9995027            Tinder         Health & Fitness
141         142  7232648             Venmo         News & Magazines
142         143  3871676              eBay                 Shopping
143         144  4556573              Zoom                  Finance
144         145   768752             Venmo                 Business
145         146  5507658         MX Player              Photography
146         147   774975           Spotify                Utilities
147         148  3039212         Pinterest            Communication
148         149  7519378          Coursera             Productivity
149         150  3144882              Lyft                 Business
150         151  8349789         Instagram            Communication
151         152  9203209          Telegram            Music & Audio
152         153  1009393            Tinder                 Business
153         154  6169650           Discord                 Business
154         155   329419            PayPal  Video Players & Editors
155         156  6535505            Airbnb                  Finance
156         157  5802160            Tinder               Navigation
157         158  9693172          Telegram             Productivity
158         159  6991662         Instagram               Navigation
159         160  8035224            Amazon                    Games
160         161  6577326         Pinterest                Education
161         162  6768663           Netflix             Productivity
162         163  5612415          Duolingo         News & Magazines
163         164  9052696            TikTok        Social Networking
164         165  8286400              Waze  Video Players & Editors
165         166   702286             Canva               Navigation
166         167  4038791          Coursera                    Games
167         168  4921419          LinkedIn        Social Networking
168         169  1616313       Google Maps            Music & Audio
169         170  1786231            Bumble         Health & Fitness
170         171   257662      Google Drive            Entertainment
171         172  4925658            Signal                Utilities
172         173  2750391          Coursera               Navigation
173         174  5897629          Coursera        Social Networking
174         175  7218722             Udemy            Music & Audio
175         176  7764433            PayPal             Productivity
176         177  5053150   Adobe Photoshop                 Business
177         178  2394774             Canva            Music & Audio
178         179  7070985            Reddit         News & Magazines
179         180  2317273      Google Drive           Travel & Local
180         181  6238070              eBay            Entertainment
181         182  4672250          OneDrive             Productivity
182         183  9450154       Google Maps            Entertainment
183         184  9518852            Airbnb                  Finance
184         185  3813925              Uber  Video Players & Editors
185         186  9162926           Spotify        Social Networking
186         187  2692464              eBay            Entertainment
187         188  6117548   Adobe Photoshop         Health & Fitness
188         189  3658545           Discord                 Business
189         190   458318            Tinder            Entertainment
190         191  4186407      Google Drive  Video Players & Editors
191         192  3542778              eBay               Navigation
192         193  9398063            Signal         Health & Fitness
193         194  3723062               VLC            Entertainment
194         195  5612314             Canva                  Finance
195         196   979109            Tinder            Communication
196         197  7162546           Spotify                  Finance
197         198  1166326              Uber  Video Players & Editors
198         199  6174006          Snapchat  Video Players & Editors
199         200  1929622          Telegram        Social Networking
200         201  3816988               VLC            Entertainment
201         202  2217143          Duolingo             Productivity
202         203  7259911  Microsoft Office                 Shopping
203         204  9521856         MX Player            Communication
204         205  5342022            Signal           Travel & Local
205         206  9440543         Grammarly  Video Players & Editors
206         207  4587028            Tinder                    Games
207         208  4684716          Coursera                 Business
208         209  5283902   Adobe Photoshop            Entertainment
209         210  2740889            PayPal                 Shopping
210         211  5542241  Microsoft Office                  Finance
211         212  1525342          Telegram                    Games
212         213  2710197  Microsoft Office        Social Networking
213         214  7516270         Grammarly                Utilities
214         215  3716647              Waze         News & Magazines
215         216  2009540         Pinterest                 Business
216         217  1960421          Duolingo                   Dating
217         218  8264342      Google Drive                   Dating
218         219  2267376          Snapchat         News & Magazines
219         220  3960617               VLC            Communication
220         221  6041939          Duolingo              Photography
221         222   809714           Dropbox                   Dating
222         223  7813396         Grammarly        Social Networking
223         224  5352285            Amazon            Entertainment
224         225  9720050           Twitter             Productivity
225         226  7107741           Twitter           Travel & Local
226         227  6895314              Lyft            Entertainment
227         228  2983553           Dropbox  Video Players & Editors
228         229  3409671       Booking.com         Health & Fitness
229         230  2664729          Coursera                   Dating
230         231  1364218             Canva        Social Networking
231         232  8389908  Microsoft Office         News & Magazines
232         233  9557911         Pinterest                Education
233         234  7631380         Pinterest                    Games
234         235  5522534          WhatsApp  Video Players & Editors
235         236  5403930             Venmo               Navigation
236         237  1245653      Google Drive                  Finance
237         238  8607186          Telegram                 Business
238         239  9836311       Google Maps         Health & Fitness
239         240   788246   Adobe Photoshop            Entertainment
240         241  2763319          LinkedIn                   Dating
241         242  4846166               VLC                Education
242         243  5776858  Microsoft Office                 Business
243         244   978547            Airbnb            Entertainment
244         245  6675963   Adobe Photoshop  Video Players & Editors
245         246  1521349            TikTok             Productivity
246         247  6419630              eBay                  Finance
247         248  2244023              eBay            Communication
248         249  8931414         MX Player                 Business
249         250  7203580          WhatsApp         Health & Fitness
250         251  1394615            PayPal             Productivity
251         252  8617619         Instagram            Music & Audio
252         253  8933734      Khan Academy            Entertainment
253         254  5749968          Duolingo               Navigation
254         255  2298638           Twitter            Entertainment
255         256  2687931            Airbnb         Health & Fitness
256         257  2877286       Google Maps        Social Networking
257         258  2421942  Microsoft Office  Video Players & Editors
258         259  7668671   Adobe Photoshop                   Dating
259         260   547451       Google Maps           Travel & Local
260         261  6751393         MX Player            Entertainment
261         262  1965405              eBay  Video Players & Editors
262         263  4086941          LinkedIn                Education
263         264  8611546              Zoom        Social Networking
264         265  5678736           Twitter               Navigation
265         266  6010597            Reddit             Productivity
266         267   803065            Amazon            Music & Audio
267         268  8746701            Bumble            Music & Audio
268         269  8042330            Bumble              Photography
269         270  3306183           YouTube           Travel & Local
270         271   902018              Lyft        Social Networking
271         272  5668772           Spotify        Social Networking
272         273  7221922           Discord                Education
273         274  3127557             Venmo               Navigation
274         275   622452              Uber         News & Magazines
275         276  6245971          Telegram                 Business
276         277  9728809          Coursera            Music & Audio
277         278  4466937       Booking.com                Utilities
278         279  5928829          Duolingo                Utilities
279         280  9327420          Snapchat                    Games
280         281  3471891      Khan Academy             Productivity
281         282  4071774      Google Drive            Music & Audio
282         283   540972          WhatsApp         Health & Fitness
283         284  9701221              Lyft            Entertainment
284         285  8130667          Facebook             Productivity
285         286  2183077      Google Drive                    Games
286         287  5202363               VLC               Navigation
287         288  5513349            PayPal             Productivity
288         289   576028              Uber         Health & Fitness
289         290  5344264          LinkedIn             Productivity
290         291  5457240           Discord                 Shopping
291         292  4259388              Lyft           Travel & Local
292         293  2773322           Discord        Social Networking